export default {
  newsData: {
    opinions: [
      {
        id: 1,
        title: '',
        text: '',
        image: '',
        creator: {
          creatorId: 1001,
          name: '',
          creatorImage: '',
        },
        category: ['', ''],
        isOpinion: true,
        isPopular: false,
        isHighlated: true,
        creationTime: Date.now(),
      },
      {
        id: 1,
        title: '',
        text: '',
        image: '',
        creator: {
          creatorId: 1001,
          name: '',
          creatorImage: '',
        },
        category: ['', ''],
        isOpinion: true,
        isPopular: false,
        isHighlated: false,
        creationTime: Date.now(),
      },
    ],
    popularNews: [
      {
        id: 1,
        title: '',
        text: '',
        image: '',
        creator: {
          creatorId: 1001,
          name: '',
          creatorImage: '',
        },
        category: ['', ''],
        isOpinion: false,
        isPopular: true,
        isHighlated: false,
        creationTime: Date.now(),
      },
      {
        id: 1,
        title: '',
        text: '',
        image: '',
        creator: {
          creatorId: 1001,
          name: '',
          creatorImage: '',
        },
        category: ['', ''],
        isOpinion: false,
        isPopular: true,
        isHighlated: false,
        creationTime: Date.now(),
      },
    ],
    news: [
      {
        id: 1,
        title: '',
        text: '',
        image: '',
        creator: {
          creatorId: 1001,
          name: '',
          creatorImage: '',
        },
        category: ['', ''],
        isOpinion: false,
        isPopular: false,
        isHighlated: true,
        creationTime: Date.now(),
      },
      {
        id: 1,
        title: '',
        text: '',
        image: '',
        creator: {
          creatorId: 1001,
          name: '',
          creatorImage: '',
        },
        category: ['', ''],
        isOpinion: false,
        isPopular: false,
        isHighlated: false,
        creationTime: Date.now(),
      },
      {
        id: 1,
        title: '',
        text: '',
        image: '',
        creator: {
          creatorId: 1001,
          name: '',
          creatorImage: '',
        },
        category: ['', ''],
        isOpinion: false,
        isPopular: false,
        isHighlated: false,
        creationTime: Date.now(),
      },
      {
        id: 1,
        title: '',
        text: '',
        image: '',
        creator: {
          creatorId: 1001,
          name: '',
          creatorImage: '',
        },
        category: ['', ''],
        isOpinion: false,
        isPopular: false,
        isHighlated: false,
        creationTime: Date.now(),
      },
      {
        id: 1,
        title: '',
        text: '',
        image: '',
        creator: {
          creatorId: 1001,
          name: '',
          creatorImage: '',
        },
        category: ['', ''],
        isOpinion: false,
        isPopular: false,
        isHighlated: false,
        creationTime: Date.now(),
      },
      {
        id: 1,
        title: '',
        text: '',
        image: '',
        creator: {
          creatorId: 1001,
          name: '',
          creatorImage: '',
        },
        category: ['', ''],
        isOpinion: false,
        isPopular: false,
        isHighlated: false,
        creationTime: Date.now(),
      },
    ],
  },
};
